"""rbac: user role/status/requested_role

Revision ID: 48bbfa0c12e6
Revises: 69c6bc598d60
Create Date: 2026-06-20 23:48:56.202776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48bbfa0c12e6'
down_revision = '69c6bc598d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        # server_default so existing rows backfill to 'active' (SQLite can't add bare NOT NULL)
        batch_op.add_column(sa.Column('status', sa.String(length=12),
                                      nullable=False, server_default='active'))
        batch_op.add_column(sa.Column('requested_role', sa.String(length=20), nullable=True))
    # backfill role for the existing seeded admin(s); others get a role at seed/approval time
    op.execute("UPDATE \"user\" SET role='admin' WHERE is_admin=1")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('requested_role')
        batch_op.drop_column('status')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
