"""add sequence table

Revision ID: 69c6bc598d60
Revises: fdd72afebc58
Create Date: 2026-06-20 22:24:48.838414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c6bc598d60'
down_revision = 'fdd72afebc58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequence',
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('prefix')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequence')
    # ### end Alembic commands ###
