"""add expected_date to SO and PO

Revision ID: fdd72afebc58
Revises: a8f5af412a16
Create Date: 2026-06-20 17:55:45.962530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd72afebc58'
down_revision = 'a8f5af412a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.drop_column('expected_date')

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_column('expected_date')

    # ### end Alembic commands ###
